######### ENGLISH VERSION BELLOW ########

##########################################
# Code à noter dans "configuration.yaml" #
##########################################

homeassistant:
  packages: !include_dir_named packages

##########################################
# Code à noter au début de "covers.yaml" #
##########################################

template:
  - cover:

# Code à noter autant de fois que vous avez d'interrupteur dans "covers.yaml"

      - name: "Nom De Votre Volet"
        device_class: shutter
        unique_id: nom_de_votre_volet_corrige
        availability: >
          {{ states('cover.ancien_nom_volet') not in ['unavailable', 'unknown'] }}
        position: >
          {% set raw = state_attr('cover.ancien_nom_volet', 'current_position') | int(default=0) %}
          {% set pos_inv = 100 - raw %}
          {% if pos_inv <= 2 %} 0
          {% elif pos_inv >= 98 %} 100
          {% else %} {{ pos_inv }}
          {% endif %}

        # Actions
        open_cover:
          action: cover.open_cover
          target:
            entity_id: cover.ancien_nom_volet
        close_cover:
          action: cover.close_cover
          target:
            entity_id: cover.ancien_nom_volet
        stop_cover:
          action: cover.stop_cover
          target:
            entity_id: cover.ancien_nom_volet
        set_cover_position:
          action: cover.set_cover_position
          target:
            entity_id: cover.ancien_nom_volet
          data:
            position: "{{ 100 - position }}"



######### ENGLISH VERSION #########

# Code to be noted in "configuration.yaml"

homeassistant:
  packages: !include_dir_named packages

# Code to be noted at the beginning of "covers.yaml"

template:
  - cover:

# Code to be noted as many times as you have switches in "covers.yaml" 

      - name: "Name of your Shutter"
        device_class: shutter
        unique_id: your_shutter_corrected
        availability: >
          {{ states('cover.your_old_shutter') not in ['unavailable', 'unknown'] }}
        position: >
          {% set raw = state_attr('cover.your_old_shutter', 'current_position') | int(default=0) %}
          {% set pos_inv = 100 - raw %}
          {% if pos_inv <= 2 %} 0
          {% elif pos_inv >= 98 %} 100
          {% else %} {{ pos_inv }}
          {% endif %}

        # Actions
        open_cover:
          action: cover.open_cover
          target:
            entity_id: cover.your_old_shutter
        close_cover:
          action: cover.close_cover
          target:
            entity_id: cover.your_old_shutter
        stop_cover:
          action: cover.stop_cover
          target:
            entity_id: cover.your_old_shutter
        set_cover_position:
          action: cover.set_cover_position
          target:
            entity_id: cover.your_old_shutter
          data:
            position: "{{ 100 - position }}"
